import { initApp } from "./game.js";

const ui = {
  startScreen: document.getElementById("start-screen"),
  soloBtn: document.getElementById("solo-btn"),
  onlineBtn: document.getElementById("online-btn"),
  onlineScreen: document.getElementById("online-screen"),
  playerName: document.getElementById("player-name"),
  roomCode: document.getElementById("room-code"),
  createRoomBtn: document.getElementById("create-room"),
  joinRoomBtn: document.getElementById("join-room"),
  roomCodeDisplay: document.getElementById("room-code-display"),
  lobbyPlayers: document.getElementById("lobby-players"),
  lobbyHint: document.getElementById("lobby-hint"),
  lobbyError: document.getElementById("lobby-error"),
  networkStatus: document.getElementById("network-status"),
  startOnlineBtn: document.getElementById("start-online"),
  lobbyBackBtn: document.getElementById("lobby-back"),
  shareLink: document.getElementById("share-link"),
  pauseMenu: document.getElementById("pause-menu"),
  resumeBtn: document.getElementById("resume-btn"),
  pauseMenuBtn: document.getElementById("pause-menu-btn"),
  endScreen: document.getElementById("end-screen"),
  endTitle: document.getElementById("end-title"),
  endReason: document.getElementById("end-reason"),
  endMoney: document.getElementById("end-money"),
  restartBtn: document.getElementById("restart-btn"),
  buyMenu: document.getElementById("buy-menu"),
  buyList: document.getElementById("buy-list"),
  health: document.getElementById("health"),
  ammo: document.getElementById("ammo"),
  weapon: document.getElementById("weapon"),
  money: document.getElementById("money"),
  timer: document.getElementById("timer"),
  teamLabel: document.getElementById("team-label"),
  bombStatus: document.getElementById("bomb-status"),
  hint: document.getElementById("hint"),
};

const game = initApp(ui);
if (game) game.run();
